export const COLORS = {
  RED: "Red",
  CYAN: "Cyan",
  BLUE: "Blue",
  NAVY: "Navy",
  LIGHT_BLUR: "Light blue",
  PINK: "Pink",
  MAGENTA: "Magenta",
  PURPLE: "Purple",
  YELLOW: "Yellow",
  ORANGE: "Orange",
  LIME: "Lime",
  GREEN: "Green",
  OLIVE: "Olive",
  MAROON: "Maroon",
  BROWN: "Brown",
  AQUA: "Aqua",
  WHITE: "White",
  SILVER: "Silver",
  GRAY: "Gray",
  GREY: "Grey",
  BLACK: "Black",
};
